// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3JWqxZzoKRrJsc2DDFbDv6
// Component: OnofSvKPZQXN

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import IconButton from "../../IconButton"; // plasmic-import: TZb0PBNLsrhB/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 3JWqxZzoKRrJsc2DDFbDv6/projectcss
import sty from "./PlasmicKvItem.module.css"; // plasmic-import: OnofSvKPZQXN/css

import CopySvgrepoComSvgIcon from "./icons/PlasmicIcon__CopySvgrepoComSvg"; // plasmic-import: JlmrLAZfJ_DH/icon

createPlasmicElementProxy;

export type PlasmicKvItem__VariantMembers = {
  noCopy: "noCopy";
  color: "blue";
  keyPosition: "left" | "center" | "right";
};
export type PlasmicKvItem__VariantsArgs = {
  noCopy?: SingleBooleanChoiceArg<"noCopy">;
  color?: SingleChoiceArg<"blue">;
  keyPosition?: SingleChoiceArg<"left" | "center" | "right">;
};
type VariantPropType = keyof PlasmicKvItem__VariantsArgs;
export const PlasmicKvItem__VariantProps = new Array<VariantPropType>(
  "noCopy",
  "color",
  "keyPosition"
);

export type PlasmicKvItem__ArgsType = {
  label?: React.ReactNode;
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicKvItem__ArgsType;
export const PlasmicKvItem__ArgProps = new Array<ArgPropType>(
  "label",
  "children"
);

export type PlasmicKvItem__OverridesType = {
  root?: Flex__<"div">;
  copy?: Flex__<typeof IconButton>;
  svg?: Flex__<"svg">;
};

export interface DefaultKvItemProps {
  label?: React.ReactNode;
  children?: React.ReactNode;
  noCopy?: SingleBooleanChoiceArg<"noCopy">;
  color?: SingleChoiceArg<"blue">;
  keyPosition?: SingleChoiceArg<"left" | "center" | "right">;
  className?: string;
}

const $$ = {};

function PlasmicKvItem__RenderFunc(props: {
  variants: PlasmicKvItem__VariantsArgs;
  args: PlasmicKvItem__ArgsType;
  overrides: PlasmicKvItem__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "noCopy",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.noCopy
      },
      {
        path: "color",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.color
      },
      {
        path: "keyPosition",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.keyPosition
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.rootcolor_blue]: hasVariant($state, "color", "blue"),
          [sty.rootkeyPosition_center]: hasVariant(
            $state,
            "keyPosition",
            "center"
          ),
          [sty.rootkeyPosition_left]: hasVariant($state, "keyPosition", "left"),
          [sty.rootkeyPosition_right]: hasVariant(
            $state,
            "keyPosition",
            "right"
          ),
          [sty.rootnoCopy]: hasVariant($state, "noCopy", "noCopy")
        }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox___0LEnG, {
          [sty.freeBoxkeyPosition_center___0LEnGkxn9I]: hasVariant(
            $state,
            "keyPosition",
            "center"
          ),
          [sty.freeBoxkeyPosition_left___0LEnGmAGlb]: hasVariant(
            $state,
            "keyPosition",
            "left"
          ),
          [sty.freeBoxkeyPosition_right___0LEnGqlYfk]: hasVariant(
            $state,
            "keyPosition",
            "right"
          ),
          [sty.freeBoxnoCopy___0LEnGEorU]: hasVariant(
            $state,
            "noCopy",
            "noCopy"
          )
        })}
      >
        <div
          className={classNames(projectcss.all, sty.freeBox__oegzm, {
            [sty.freeBoxcolor_blue__oegzmW9TSd]: hasVariant(
              $state,
              "color",
              "blue"
            )
          })}
        >
          {renderPlasmicSlot({
            defaultContents: "\u30ad\u30fc\u540d",
            value: args.label,
            className: classNames(sty.slotTargetLabel, {
              [sty.slotTargetLabelcolor_blue]: hasVariant(
                $state,
                "color",
                "blue"
              )
            })
          })}
        </div>
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__dwut6, {
          [sty.freeBoxcolor_blue__dwut6W9TSd]: hasVariant(
            $state,
            "color",
            "blue"
          )
        })}
      >
        <div
          className={classNames(projectcss.all, sty.freeBox__ho0Bl, {
            [sty.freeBoxnoCopy__ho0BlEorU]: hasVariant(
              $state,
              "noCopy",
              "noCopy"
            )
          })}
        >
          <div className={classNames(projectcss.all, sty.freeBox__jxfw6)}>
            {renderPlasmicSlot({
              defaultContents:
                "\u30d0\u30ea\u30e5\u30fc\u540d\u304c\u30d0\u30ea\u30e5\u30fc\u540d\u304c\u30d0\u30ea\u30e5\u30fc\u540d\u304c\u30d0\u30ea\u30e5\u30fc\u540d\u304c\u30d0\u30ea\u30e5\u30fc\u540d\u304c\u30d0\u30ea\u30e5\u30fc\u540d\u304c\u30d0\u30ea\u30e5\u30fc\u540d\u304c\u30d0\u30ea\u30e5\u30fc\u540d\u304c\u30d0\u30ea\u30e5\u30fc\u540d\u304c\u30d0\u30ea\u30e5\u30fc\u540d\u304c\u30d0\u30ea\u30e5\u30fc\u540d\u304c\u30d0\u30ea\u30e5\u30fc\u540d\u304c\u30d0\u30ea\u30e5\u30fc\u540d\u304c",
              value: args.children
            })}
          </div>
          {(hasVariant($state, "noCopy", "noCopy") ? false : true) ? (
            <IconButton
              data-plasmic-name={"copy"}
              data-plasmic-override={overrides.copy}
              className={classNames("__wab_instance", sty.copy, {
                [sty.copynoCopy]: hasVariant($state, "noCopy", "noCopy")
              })}
            >
              <CopySvgrepoComSvgIcon
                data-plasmic-name={"svg"}
                data-plasmic-override={overrides.svg}
                className={classNames(projectcss.all, sty.svg)}
                role={"img"}
              />
            </IconButton>
          ) : null}
        </div>
      </div>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "copy", "svg"],
  copy: ["copy", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  copy: typeof IconButton;
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicKvItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicKvItem__VariantsArgs;
    args?: PlasmicKvItem__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicKvItem__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicKvItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicKvItem__ArgProps,
          internalVariantPropNames: PlasmicKvItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicKvItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicKvItem";
  } else {
    func.displayName = `PlasmicKvItem.${nodeName}`;
  }
  return func;
}

export const PlasmicKvItem = Object.assign(
  // Top-level PlasmicKvItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    copy: makeNodeComponent("copy"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicKvItem
    internalVariantProps: PlasmicKvItem__VariantProps,
    internalArgProps: PlasmicKvItem__ArgProps
  }
);

export default PlasmicKvItem;
/* prettier-ignore-end */
