apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml
  - manpoko.yaml
  - ingress.yaml

configMapGenerator:
  - name: backend-config
    files:
      - backend-config.json
  - name: manpoko-config
    files:
      - manpoko-config.json
