apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  tls:
    - hosts:
        - "usagiverify.mynacard.app"
        - "*.usagiverify.mynacard.app"
      secretName: service-tls
  rules:
    - host: backend.usagiverify.mynacard.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
